disabled-gamemodes: []

range-upgrades:
  enabled: true
  max-range: 500
  slot: 11
  levels:
    1:
      range: 50
    2:
      range: 100
      cost: 500
    3:
      range: 150
      cost: 1000
    4:
      range: 200
      cost: 1500
    5:
      range: 250
      cost: 2000

member-upgrades:
  enabled: true
  slot: 13
  levels:
    1:
      members: 2
    2:
      members: 3
      cost: 500
    3:
      members: 4
      cost: 1000

hopper-upgrades:
  enabled: true
  slot: 15
  levels:
    1:
      hoppers: 5
    2:
      hoppers: 12
      cost: 500
    3:
      hoppers: 20
      cost: 700
    4:
      hoppers: 30
      cost: 900
    5:
      hoppers: 50
      cost: 1100